# Numpy

https://www.youtube.com/watch?v=DcfYgePyedM

In [2]:
import numpy as np

## Criando Arrays

In [8]:
# Criando um vetor simples
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
#Criando uma matriz simples
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)
print(np.shape(b))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [16]:
#Vetores de zeros
c = np.zeros(10)
print(c)
d = np.zeros((3,3))
print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Vetores de 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
# Create an empty array with 2 elements
np.empty(2) 

array([0., 0.])

In [24]:
# Criando sequencias 
e = np.arange(10)
print(e)
f = np.arange(2,9,2)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [29]:
# Outra forma de criar vetor sequencial
A = np.linspace(0, 10, 5)
print(A)
B = np.linspace(0, 33, 12)
print(B)

[ 0.   2.5  5.   7.5 10. ]
[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]


In [31]:
# Números aleatórios de 0 a 1
a4 = np.random.random(10)
print(a4)

[0.25872477 0.08844344 0.87968942 0.48499276 0.01215796 0.55152505
 0.01142555 0.77707658 0.23422483 0.0503854 ]


In [32]:
a5 = np.random.randn(10)
print(a5)

[-0.84937238  0.36126718 -0.41320173  1.44927185 -0.28082651 -1.14154834
  1.22088062 -1.12018239 -0.61408143 -1.47805953]


## Adicionando, removendo e ordenando elementos

In [33]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [35]:
# Ordenando o array
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8])

In [39]:
np.concatenate((a, b))


array([1, 2, 3, 4, 5, 5, 6, 7, 8])

In [40]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [44]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [47]:
print(array_example.ndim)
print(array_example.size)
print(array_example.shape)

3
24
(3, 2, 4)


In [49]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [52]:
b = np.append(a, 5)
print(b)

[1 2 3 4 5]


In [55]:
np.delete(b, 4) # deleta o número do elemento (ou sub-array)

array([1, 2, 3, 4])

In [58]:
# Redimensionando
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [59]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


# Indexing and slicing
https://numpy.org/doc/stable/user/absolute_beginners.html


In [3]:
data = np.array([1, 2, 3])

In [4]:
data[1] # o contador começa do 0, então a indexação 1 é o segundo elemento

2

In [5]:
data[0:2] # começa do elemento 0 e vai até o segundo, mas não conta o número 2, não está incluso.

array([1, 2])

In [6]:
data[1:] # todos os elementos a partir do segundo

array([2, 3])

In [8]:
data[-2:] # pega os dois últimos elementos do array

array([2, 3])

In [9]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [10]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a[a < 5]

array([1, 2, 3, 4])

In [12]:
print(a[a<5])

[1 2 3 4]


In [13]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [14]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [15]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## Basic array operations

In [19]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data)
print(ones)
# soma de vetores
data + ones

[1 2]
[1 1]


array([2, 3])

In [20]:
#subtração
data - ones

array([0, 1])

In [21]:
# Multiplicação
data * data

array([1, 4])

In [22]:
# Divisão
data/data

array([1., 1.])

In [24]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [30]:
# Soma dos elementos do array
a.sum()

10

In [27]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [28]:
b.sum(axis=0)

array([3, 3])

In [29]:
b.sum(axis=1)

array([2, 4])

In [31]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
data[0, 1]

2

In [33]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [34]:
data[0:2, 0]

array([1, 3])

In [35]:
data.max()

6

In [36]:
data.min()

1

In [37]:
data.sum()

21

In [38]:
data.max(axis=0)

array([5, 6])

In [39]:
data.max(axis=1)

array([2, 4, 6])

In [41]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [42]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [46]:
data = np.array([1, 2, 3, 4, 5, 6])

In [49]:
arr = data.reshape(2,3)

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [54]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])